"use client";
import { useEffect } from "react";
import type { Metadata } from "next";
import HeaderComponent from "./components/header.component";
import "./globals.css";
import FooterComponent from "./components/footer.component";
import { FloatingNavDemo } from "./components/floating-navbar.component";
import { ConfigProvider } from "antd";
import { usePathname } from "next/navigation";
import GoogleTagManager from "./components/GoogleTagManager/gtm.component";
import ClarityAnalytics from "./components/ClarityAnalytics/clarity.component";
import GoogleAnalyticsManager from "./components/GoogleAnalyticsComponent/gtm-analytics.component";
// export const metadata: Metadata = {
//   title: "Triorama",
//   description: "Generated by create next app",
// };
const mapping: { [key: string]: string } = {
  "/pricing": "Pricing",
  "/contact-sales": "Contact Sales",
  "/company": "Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  useEffect(() => {
    const pageTitle = mapping[pathname] || "Triorama";
    document.title = pageTitle;
  }, [pathname]);
  return (
    <html lang="en">
      <meta name="google-site-verification" content="Q8czXYFXuepViArWxuPgRbqFOyA6NnfyGNpzzst6B-s" />
      <GoogleAnalyticsManager />
      <GoogleTagManager />
      <ClarityAnalytics />
      <body>
        {/* <NavbarComponent /> */}
        <ConfigProvider
          theme={{
            components: {
              Select: {
                colorBgContainer: "#FEFEFE",
                borderRadius: 20,
              },
            },
          }}
        >
          <FloatingNavDemo />
          {children}
          <FooterComponent />
        </ConfigProvider>
      </body>
    </html>
  );
}
